language: node_js
node_js:
  - 'node'
  - 'lts/*'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script: yarn run pretest
install: yarn install --ignore-engines
cache:
  yarn: true
  directories:
    - node_modules
script: yarn run test:ci
after_script: yarn run coveralls
